### ISSUE TITLE
트레이(메뉴막대)에 시간 표시

### ISSUE THREAD

**Issue by dbrud60yk** [hyun6/pomodoro-timer#9]
![스크린샷 2023-02-12 19 38 22](https://user-images.githubusercontent.com/67114132/218306127-ba7770ec-ea68-4a9c-a585-e1a3e5291b19.png)

- 아이콘 표시
- 남은 시간 표시 
- 클릭 시 앱 포커스 상태로 띄우기 (카톡이나 멜론처럼)

**Comment by hyun6** [comment]
ref: https://www.reddit.com/r/FlutterDev/comments/g7aavn/creating_a_menubar_app_for_macos/

**Comment by hyun6** [comment]
using system_tray package
 - https://pub.dev/packages/system_tray
